source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CTVideoView_Example', :exclusive => true do
  pod "CTVideoView", :path => "../"
end

target 'CTVideoView_Tests', :exclusive => true do
  pod "CTVideoView", :path => "../"

  
end
